server {
    listen 80;
    listen [::]:80;
    server_name cristinapsi.online;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/psi-acme;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name cristinapsi.online;

    ssl_certificate /etc/letsencrypt/live/cristinapsi.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cristinapsi.online/privkey.pem;

    location / {
        default_type text/plain;
        return 200 "Site em preparacao.\n";
    }
}
